-- MecaData Atributos
ALTER TABLE Vehiculos ADD CONSTRAINT CK_VEHICULOS_KILOMETRAJE
    CHECK (kilometraje >= 0);

ALTER TABLE Vehiculos ADD CONSTRAINT CK_VEHICULOS_CILINDRAJE
    CHECK (cilindraje > 0);

ALTER TABLE Empleados ADD CONSTRAINT CK_EMPLEADOS_SALARIO
    CHECK (salario > 0);

ALTER TABLE CatalogoServicios ADD CONSTRAINT CK_CATALOGO_SERVICIOS_PRECIO_BASE
    CHECK (precioBase > 0);

ALTER TABLE CatalogoServicios ADD CONSTRAINT CK_CATALOGO_SERVICIOS_TIEMPO_MEDIO
    CHECK (tiempoMedio > 0);

ALTER TABLE Presta ADD CONSTRAINT CK_PRESTA_PRECIO_LOCAL
    CHECK (precioLocal > 0);

ALTER TABLE Trabaja ADD CONSTRAINT CK_TRABAJA_HORAS_TRABAJADAS
    CHECK (horasTrabajadas > 0);

ALTER TABLE Inventario ADD CONSTRAINT CK_INVENTARIO_CANTIDAD
    CHECK (cantidad >= 0);

ALTER TABLE Traslados ADD CONSTRAINT CK_TRASLADOS_CANTIDAD
    CHECK (cantidad > 0);

ALTER TABLE ConsumoRepuesto ADD CONSTRAINT CK_CONSUMO_REPUESTO_CANTIDAD
    CHECK (cantidad > 0);

ALTER TABLE DetalleCompras ADD CONSTRAINT CK_DETALLE_COMPRAS_CANTIDAD
    CHECK (cantidad > 0);
