-- MecaData Foraneas
ALTER TABLE Automoviles ADD CONSTRAINT FK_AUTOMOVILES_VEHICULO
    FOREIGN KEY (vehiculo) REFERENCES Vehiculos(placa)
    ON DELETE CASCADE;

ALTER TABLE Vehiculos ADD CONSTRAINT FK_VEHICULOS_CLIENTE
    FOREIGN KEY (cliente) REFERENCES Clientes(persona)
    ON DELETE RESTRICT;

ALTER TABLE Clientes ADD CONSTRAINT FK_CLIENTES_PERSONA
    FOREIGN KEY (persona) REFERENCES Personas(cedula)
    ON DELETE CASCADE;

ALTER TABLE Empleados ADD CONSTRAINT FK_EMPLEADOS_PERSONA
    FOREIGN KEY (persona) REFERENCES Personas(cedula)
    ON DELETE CASCADE;

ALTER TABLE Empleados ADD CONSTRAINT FK_EMPLEADOS_SEDE
    FOREIGN KEY (sede) REFERENCES Sedes(numero)
    ON DELETE RESTRICT;

ALTER TABLE Tecnicos ADD CONSTRAINT FK_TECNICOS_EMPLEADO
    FOREIGN KEY (empleado) REFERENCES Empleados(persona)
    ON DELETE CASCADE;

ALTER TABLE Trabaja ADD CONSTRAINT FK_TRABAJA_TECNICO
    FOREIGN KEY (tecnico) REFERENCES Tecnicos(empleado)
    ON DELETE RESTRICT;

ALTER TABLE Trabaja ADD CONSTRAINT FK_TRABAJA_DETALLE_ORDEN
    FOREIGN KEY (detalleOrden) REFERENCES DetalleOrdenes(id)
    ON DELETE CASCADE;

ALTER TABLE DetalleOrdenes ADD CONSTRAINT FK_DETALLE_ORDENES_CATALOGO_SERVICIO
    FOREIGN KEY (catalogoServicio) REFERENCES CatalogoServicios(codigo)
    ON DELETE RESTRICT;

ALTER TABLE DetalleOrdenes ADD CONSTRAINT FK_DETALLE_ORDENES_SERVICIO
    FOREIGN KEY (servicio) REFERENCES Servicios(numero)
    ON DELETE CASCADE;

ALTER TABLE Garantias ADD CONSTRAINT FK_GARANTIAS_DETALLE_ORDEN
    FOREIGN KEY (detalleOrden) REFERENCES DetalleOrdenes(id)
    ON DELETE RESTRICT;

ALTER TABLE Servicios ADD CONSTRAINT FK_SERVICIOS_VEHICULO
    FOREIGN KEY (vehiculo) REFERENCES Vehiculos(placa)
    ON DELETE RESTRICT;

ALTER TABLE Servicios ADD CONSTRAINT FK_SERVICIOS_SEDE
    FOREIGN KEY (sede) REFERENCES Sedes(numero)
    ON DELETE RESTRICT;

ALTER TABLE Presta ADD CONSTRAINT FK_PRESTA_CATALOGO_SERVICIO
    FOREIGN KEY (catalogoServicio) REFERENCES CatalogoServicios(codigo)
    ON DELETE RESTRICT;

ALTER TABLE Presta ADD CONSTRAINT FK_PRESTA_SEDE
    FOREIGN KEY (sede) REFERENCES Sedes(numero)
    ON DELETE RESTRICT;

ALTER TABLE Inventario ADD CONSTRAINT FK_INVENTARIO_SEDE
    FOREIGN KEY (sede) REFERENCES Sedes(numero)
    ON DELETE RESTRICT;

ALTER TABLE Inventario ADD CONSTRAINT FK_INVENTARIO_REPUESTO
    FOREIGN KEY (repuesto) REFERENCES Repuestos(serie)
    ON DELETE RESTRICT;

ALTER TABLE Traslados ADD CONSTRAINT FK_TRASLADOS_SEDE_LLEGA
    FOREIGN KEY (sedeLlega) REFERENCES Sedes(numero)
    ON DELETE RESTRICT;

ALTER TABLE Traslados ADD CONSTRAINT FK_TRASLADOS_SEDE_SALE
    FOREIGN KEY (sedeSale) REFERENCES Sedes(numero)
    ON DELETE RESTRICT;

ALTER TABLE ConsumoRepuesto ADD CONSTRAINT FK_CONSUMO_REPUESTO_REPUESTO
    FOREIGN KEY (repuesto) REFERENCES Repuestos(serie)
    ON DELETE RESTRICT;

ALTER TABLE ConsumoRepuesto ADD CONSTRAINT FK_CONSUMO_REPUESTO_DETALLE_ORDEN
    FOREIGN KEY (detalleOrden) REFERENCES DetalleOrdenes(id)
    ON DELETE CASCADE;

ALTER TABLE Suministra ADD CONSTRAINT FK_SUMINISTRA_PROVEEDOR
    FOREIGN KEY (proveedor) REFERENCES Proveedores(nit)
    ON DELETE RESTRICT;

ALTER TABLE Suministra ADD CONSTRAINT FK_SUMINISTRA_REPUESTO
    FOREIGN KEY (repuesto) REFERENCES Repuestos(serie)
    ON DELETE RESTRICT;

ALTER TABLE Compras ADD CONSTRAINT FK_COMPRAS_SEDE
    FOREIGN KEY (sede) REFERENCES Sedes(numero)
    ON DELETE RESTRICT;

ALTER TABLE Compras ADD CONSTRAINT FK_COMPRAS_PROVEEDOR
    FOREIGN KEY (proveedor) REFERENCES Proveedores(nit)
    ON DELETE RESTRICT;

ALTER TABLE DetalleCompras ADD CONSTRAINT FK_DETALLE_COMPRAS_COMPRA
    FOREIGN KEY (compra) REFERENCES Compras(numero)
    ON DELETE CASCADE;

ALTER TABLE DetalleCompras ADD CONSTRAINT FK_DETALLE_COMPRAS_REPUESTO
    FOREIGN KEY (repuesto) REFERENCES Repuestos(serie)
    ON DELETE RESTRICT;

ALTER TABLE Cobros ADD CONSTRAINT FK_COBROS_MOVIMIENTO
    FOREIGN KEY (movimiento) REFERENCES Movimientos(numero)
    ON DELETE RESTRICT;

ALTER TABLE Cobros ADD CONSTRAINT FK_COBROS_ORDEN
    FOREIGN KEY (orden) REFERENCES Servicios(numero)
    ON DELETE RESTRICT;

ALTER TABLE Pagos ADD CONSTRAINT FK_PAGOS_MOVIMIENTO
    FOREIGN KEY (movimiento) REFERENCES Movimientos(numero)
    ON DELETE RESTRICT;

ALTER TABLE Pagos ADD CONSTRAINT FK_PAGOS_COMPRA
    FOREIGN KEY (compra) REFERENCES Compras(numero)
    ON DELETE RESTRICT;

ALTER TABLE Traslados ADD CONSTRAINT FK_TRASLADOS_REPUESTO
    FOREIGN KEY (repuesto) REFERENCES Repuestos(serie)
    ON DELETE RESTRICT;
