-- MecaData Primarias
ALTER TABLE Automoviles ADD CONSTRAINT PK_AUTOMOVILES
    PRIMARY KEY (vehiculo);

ALTER TABLE Vehiculos ADD CONSTRAINT PK_VEHICULOS
    PRIMARY KEY (placa);

ALTER TABLE Clientes ADD CONSTRAINT PK_CLIENTES
    PRIMARY KEY (persona);

ALTER TABLE Personas ADD CONSTRAINT PK_PERSONAS
    PRIMARY KEY (cedula);  

ALTER TABLE Empleados ADD CONSTRAINT PK_EMPLEADOS
    PRIMARY KEY (persona);

ALTER TABLE Tecnicos ADD CONSTRAINT PK_TECNICOS
    PRIMARY KEY (empleado);

ALTER TABLE Trabaja ADD CONSTRAINT PK_TRABAJA
    PRIMARY KEY (tecnico, detalleOrden);

ALTER TABLE DetalleOrdenes ADD CONSTRAINT PK_DETALLE_ORDENES
    PRIMARY KEY (id);  

ALTER TABLE Garantias ADD CONSTRAINT PK_GARANTIAS
    PRIMARY KEY (numero);

ALTER TABLE Servicios ADD CONSTRAINT PK_SERVICIOS
    PRIMARY KEY (numero);

ALTER TABLE CatalogoServicios ADD CONSTRAINT PK_CATALOGO_SERVICIOS
    PRIMARY KEY (codigo);

ALTER TABLE Presta ADD CONSTRAINT PK_PRESTA
    PRIMARY KEY (catalogoServicio, sede);

ALTER TABLE Sedes ADD CONSTRAINT PK_SEDES
    PRIMARY KEY (numero);

ALTER TABLE Inventario ADD CONSTRAINT PK_INVENTARIO
    PRIMARY KEY (sede, repuesto);

ALTER TABLE Repuestos ADD CONSTRAINT PK_REPUESTOS
    PRIMARY KEY (serie);

ALTER TABLE Traslados ADD CONSTRAINT PK_TRASLADOS
    PRIMARY KEY (numero);

ALTER TABLE ConsumoRepuesto ADD CONSTRAINT PK_CONSUMO_REPUESTO
    PRIMARY KEY (repuesto, detalleOrden);

ALTER TABLE Suministra ADD CONSTRAINT PK_SUMINISTRA
    PRIMARY KEY (proveedor, repuesto);

ALTER TABLE Proveedores ADD CONSTRAINT PK_PROVEEDORES
    PRIMARY KEY (nit);

ALTER TABLE Compras ADD CONSTRAINT PK_COMPRAS
    PRIMARY KEY (numero);

ALTER TABLE DetalleCompras ADD CONSTRAINT PK_DETALLE_COMPRAS
    PRIMARY KEY (id);

ALTER TABLE Movimientos ADD CONSTRAINT PK_MOVIMIENTOS
    PRIMARY KEY (numero);

ALTER TABLE Cobros ADD CONSTRAINT PK_COBROS
    PRIMARY KEY (movimiento);

ALTER TABLE Pagos ADD CONSTRAINT PK_PAGOS
    PRIMARY KEY (movimiento);
