-- MecaData Unicas
ALTER TABLE Personas ADD CONSTRAINT UK_PERSONAS_CORREO
    UNIQUE (correo);

ALTER TABLE Garantias ADD CONSTRAINT UK_GARANTIAS_DETALLE_ORDEN
    UNIQUE (detalleOrden);

ALTER TABLE Sedes ADD CONSTRAINT UK_SEDES_TELEFONO
    UNIQUE (telefono);

ALTER TABLE Proveedores ADD CONSTRAINT UK_PROVEEDORES_CORREO
    UNIQUE (correo);

ALTER TABLE Proveedores ADD CONSTRAINT UK_PROVEEDORES_NUMERO_CONTACTO
    UNIQUE (numeroContacto);

ALTER TABLE Cobros ADD CONSTRAINT UK_COBROS_ORDEN
    UNIQUE (orden);

ALTER TABLE Pagos ADD CONSTRAINT UK_PAGOS_COMPRA
    UNIQUE (compra);
